---
version: '3'

services:
  drupal:
    # rename it for each project like
    #image: amutylo/site-name:latest
    image: geerlingguy/drupal-for-kubernetes:latest
    #rename this like
    #container_name: site-name
    container_name: drupal-for-kubernetes
    environment:
      DRUPAL_DATABASE_HOST: 'mysql'
      DRUPAL_DATABASE_PORT: '3306'
      DRUPAL_DATABASE_NAME: 'drupal'
      DRUPAL_DATABASE_USERNAME: 'drupal'
      DRUPAL_DATABASE_PASSWORD: 'drupal'
      #TODO:: reuse hash salt is ok for local env, change for prod.
      DRUPAL_HASH_SALT: 'fe918c992fb1bcfa01f32303c8b21f3d0a0'
      DRUPAL_DOWNLOAD_IF_NOT_PRESENT: 'false'
    ports:
      - "80:80"
    restart: on-failure
    # Share the project into the container for local development. Comment out
    # this line to test the production-ready pre-built container codebase.
    # delegated is important mac os settings, use it only for mac os
    volumes: ['./:/var/www/html:rw,delegated']

  mysql:
    image: mysql:5.7
    container_name: drupal-mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    restart: on-failure
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql
